version: 2

sources:
  - name: "{{ var('source_name') }}"
    database: "{{ var('source_database') }}"
    schema:  "{{ var('source_schema') }}"
    tables:
      - name: medical_claim
      - name: memmber_month
      - name: memmber_demographic